# Linear algebra
  Determinant
  Trace
  Singular Vector Decomposition
  Eigenvalues
  Matrix Norm
  Inverse
  etc...

In [2]:
import numpy as np

In [4]:
a = np.ones((2,3))  # recuerda que el No. de columnas de la primera matrix, deben
print(a)   # ser iguales al No. de filas de la segunda matrix

b = np.full((3,2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [6]:
np.matmul(a,b)  #Multiplica matrices

array([[6., 6.],
       [6., 6.]])

In [8]:
# Find the determinant
c = np.identity(3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
np.linalg.det(c)

1.0

In [ ]:
# https://docs.scipy.org/doc/numpy-1.13...
# https://www.youtube.com/redirect?redir_token=QUFFLUhqbHBrYjdyZ040V25nWlFUclNJa0pOSEZ0RGJDZ3xBQ3Jtc0tuQmNSUVRyLWVyNlF1bFE5ei05MzN0RjJycEhtTDdyc2xOY25YMm1FOU15MHhOMzBLbmc1Mk1Dd0x4UXUzdWNOVG5ZWUR6cEVJNUh3VHdqRnNKdHcyVVkyTnV0eFM2cXJQTVU1czhxNVEwczVSUFpWaw%3D%3D&event=video_description&v=GB9ByFAIAH4&q=https%3A%2F%2Fdocs.scipy.org%2Fdoc%2Fnumpy%2Freference%2Froutines.array-creation.html
# https://www.youtube.com/redirect?redir_token=QUFFLUhqa0hsMElxUldEZUo2bjk5cW01d0FZV0RXLXJOZ3xBQ3Jtc0tucVBoTXowSUZ5SW5QTmVVSFlXUlR4LUc2NHdSSXB3aVlScGVpcW1Ld2k1RlJZcGtNXzhqdnN2Q1JhNnJZb21ILXAxbTlDc3J6MVozNlM2ZFBRZlJTVkN4bjVwaEZEUHE3Y2hxcy11alNEeTVBVnA4RQ%3D%3D&event=video_description&v=GB9ByFAIAH4&q=https%3A%2F%2Fdocs.scipy.org%2Fdoc%2Fnumpy%2Freference%2Froutines.math.html
# https://www.youtube.com/redirect?redir_token=QUFFLUhqbU9oZ3F0LW5Lb2dmVm1FSGF6SzlUWDZlOUtHQXxBQ3Jtc0trYUZTeHJHeTBXeC1JUG1zN3lhanVrSHAwUE1IbmV2YXZsU19TMEpKMV9EdFg4Q0xaZnhkVkFsWHNha0tjYmxDX1gyTEowc09yRnVMX2FSWldZVV8zYmlYODdxVDd6VmJWeU5nUmN5anY3dklWT2oxaw%3D%3D&event=video_description&v=GB9ByFAIAH4&q=https%3A%2F%2Fdocs.scipy.org%2Fdoc%2Fnumpy%2Freference%2Froutines.linalg.html


### Statistics

In [11]:
stats = np.array([[1,4,7],[3,6,9]])
stats

array([[1, 4, 7],
       [3, 6, 9]])

In [17]:
np.min(stats, axis=0)

array([1, 4, 7])

In [14]:
np.min(stats, axis=1)

array([1, 3])

In [15]:
np.max(stats, axis = 0)

array([3, 6, 9])

In [16]:
np.max(stats, axis = 1)

array([7, 9])

In [18]:
np.sum(stats)

30

In [19]:
np.sum(stats, axis = 0)

array([ 4, 10, 16])

In [20]:
np.sum(stats, axis = 1)

array([12, 18])

### Reorganizing arrays

In [21]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [22]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)

(2, 4)


In [24]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)



[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [25]:
# Vertically stacking vectors

v1= np.array([1,2,3,4])
v2= np.array([5,6,7,8])

np.vstack([v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
# Vertically stacking vectors

v1= np.array([1,2,3,4])
v2= np.array([5,6,7,8])

np.vstack([v1, v2, v1, v2, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [27]:
# Horizontal stack

h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneus
Load data from file

In [ ]:
 #    filedate =  np.genfromtxt('data.txt', delimeter=',')
    #filedate.astype('int32')

Boolean masking and advanced indexing

In [28]:
after > 3

array([[False, False],
       [False,  True],
       [ True,  True],
       [ True,  True]])

In [30]:
after[after>3]

array([4, 5, 6, 7, 8])

In [31]:
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [32]:
## You can index with a list in NumPy

a = np.array([1,2,3,4,5,6,7,8,9])
a[[3,6,8]]

array([4, 7, 9])

In [33]:
np.any(after > 2, axis =0)

array([ True,  True])

In [36]:
np.any(after > 2, axis =1)

array([False,  True,  True,  True])

In [34]:
np.all(after > 2, axis =0)

array([False, False])

In [35]:
np.all(after > 2, axis =1)

array([False,  True,  True,  True])

In [38]:
((after >1) & (after <3))

array([[False,  True],
       [False, False],
       [False, False],
       [False, False]])

In [41]:
(~((after >1) & (after <3)))

array([[ True, False],
       [ True,  True],
       [ True,  True],
       [ True,  True]])